from PyQt5.QtWidgets import (QApplication, QWidget, QPushButton, QVBoxLayout, QLabel,
                              QSpinBox, QGroupBox, QHBoxLayout, QRadioButton, QButtonGroup)
from PyQt5.QtCore import Qt
menu = QPushButton('Menu')
rest = QPushButton('Rest')
vidpovid = QPushButton('Відповісти')
sPIN = QSpinBox()
sPIN.setValue(30)
groupa = QGroupBox('varianti')
groupa2 = QGroupBox('Answer')
quest_lb = QLabel('Запитання')
buhanka1 = QRadioButton('aple')
buhanka2 = QRadioButton('cut')
buhanka3 = QRadioButton('apple')
buhanka4 = QRadioButton('snukel')
buh_menu1 = QPushButton('СТАРТ')
buh_menu2 = QPushButton('НАВЧАННЯ')
buh_menu3 = QPushButton('ВИЙТИ')
groupa2.hide()
answer = QLabel('Correct')
answerr = QLabel('')
main_line_quizzi = QVBoxLayout()
main_menu = QVBoxLayout()
line1_quizzi = QHBoxLayout()
layout_golovnii = QHBoxLayout()
layout_golovnii2 = QHBoxLayout()
layout = QVBoxLayout()
layout2 = QVBoxLayout()
layout1 = QVBoxLayout()
layout_groupa2 = QVBoxLayout()
korobka = QButtonGroup()
answer_layout = QVBoxLayout()
korobka.addButton(buhanka1)
korobka.addButton(buhanka2)
korobka.addButton(buhanka3)
korobka.addButton(buhanka4)

line1_quizzi.addWidget(menu)
line1_quizzi.addStretch(1)
line1_quizzi.addWidget(rest)
line1_quizzi.addWidget(sPIN)
line1_quizzi.addWidget(QLabel('Хвилин'))

layout.addWidget(buhanka1)
layout.addWidget(buhanka2)
layout2.addWidget(buhanka3)
layout2.addWidget(buhanka4)
main_line_quizzi.addLayout(line1_quizzi)
main_line_quizzi.addWidget(quest_lb, alignment=Qt.AlignCenter)
layout_golovnii.addLayout(layout)
layout_golovnii.addLayout(layout2)
layout_golovnii2.addLayout(layout1)
answer_layout.addWidget(answerr)

layout_golovnii2.addWidget(answer)

main_line_quizzi.addWidget(groupa)
main_line_quizzi.addWidget(groupa2)
groupa.setLayout(layout_golovnii)
groupa2.setLayout(layout_golovnii2)
main_line_quizzi.addWidget(vidpovid)


main_menu.addWidget(buh_menu1, alignment=Qt.AlignCenter)
main_menu.addWidget(buh_menu2, alignment=Qt.AlignCenter)
main_menu.addWidget(buh_menu3, alignment=Qt.AlignCenter)


rbtns = [buhanka1, buhanka2, buhanka3, buhanka4]